language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - bin/conda install --force --no-deps conda requests
  - conda --version
  - conda install conda-server ipython-notebook mock nose
  - if [[ "$PYCOSAT" ]]; then
      conda install pycosat=$PYCOSAT;
    fi
  - python setup.py install
  - conda info -a

script:
  - nosetests
  - conda --help

sudo: false
