language: python
python:
- '2.7'
- '3.4'
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes
- conda --version
- conda install anaconda-client nbformat mock nose jinja2
- if [[ "$PYCOSAT" ]]; then conda install pycosat=$PYCOSAT; fi
- python setup.py install
script:
- nosetests
- conda env --help
sudo: false
notifications:
  email: false
  flowdock:
    secure: QH1eDdrLEHrRQnBNNqITB1XoEiz0Dey0LzL1VZl06KJINRoOvDiM4uZU6pC7odU7r+Bwxv0YTqY6tZZDQSDwzJpLqyxX7KJwNwIgU13sD7NLGdh0Ll8o8fZOS0sIu6xsFKh7X0PPTTGV0FCYUrzft0drM8jjPCRV4Ayn5wlGc/g=
